{% set name = "stackprinter" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 271efc75ebdcc1554e58168ea7779f98066d54a325f57c7dc19f10fa998ef01e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - stackprinter

about:
  home: https://github.com/cknd/stackprinter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Debugging-friendly exceptions for Python

extra:
  recipe-maintainers:
    - scopatz
    - tetov
