{% set name = "stackprinter" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0197c54dafe7867020731c3dcab96a14d103c1e39130fa0b5159a2f0af427b6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - stackprinter

about:
  home: https://github.com/cknd/stackprinter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Debugging-friendly exceptions for Python

extra:
  recipe-maintainers:
    - scopatz
