{% set name = "stackprinter" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 032adf196355e323a25f29de312ea0ba8077036443e4c9ddb55f83fb03d3685d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - stackprinter

about:
  home: https://github.com/cknd/stackprinter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Debugging-friendly exceptions for Python

extra:
  recipe-maintainers:
    - scopatz
