schema_version: 1

context:
  version: "0.2.13"

package:
  name: stackprinter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/stackprinter/stackprinter-${{ version }}.tar.gz
  sha256: 6532f2473675927e38e0241212a341549c5d1329446d2b771bb9b1db8ecfca8e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - stackprinter
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Debugging-friendly exceptions for Python
  homepage: https://github.com/cknd/stackprinter

extra:
  recipe-maintainers:
    - scopatz
    - tetov
